# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.form.animaux:
        class: AppBundle\Form\AnimauxType
        arguments:
            - '@security.token_storage'
        tags:
            - { name: form.type}
    app.form.accouplement:
        class: AppBundle\Form\AccouplementType
        arguments:
            - '@security.token_storage'
        tags:
            - { name: form.type}
    app.event.animal:
        class: AppBundle\Event\AnimalEvent
    app.event.accouplement:
        class: AppBundle\Event\AccouplementEvent
    app.animal_subscriber:
        class: AppBundle\EventListener\AnimalSubscriber
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: kernel.event_subscriber }
    app.accouplement_subscriber:
        class: AppBundle\EventListener\AccouplementSubscriber
        tags:
            - {name: kernel.event_subscriber}