# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.form.animaux:
        class: AppBundle\Form\AnimauxType
        arguments:
            - '@security.token_storage'
        tags:
            - { name: form.type}
    app.form.accouplement:
        class: AppBundle\Form\AccouplementType
        arguments:
            - '@security.token_storage'
        tags:
            - { name: form.type}
    app.event.animal.add:
        class: AppBundle\Event\AnimalEvent
        tags:
            - {name: animal.event_add}
    app.eventlistener.animal:
        class: AppBundle\EventListener\AnimalListener
        arguments:
            - '@app.validateur.accouplement'
        tags:
            - { name: kernel.event_listener, event:app.event.animal.add, method: verifAdd}