animaux_index:
    path:     /
    defaults: { _controller: "AppBundle:Animaux:index" }
    methods:  GET

animaux_show:
    path:     /{id}/show/
    defaults: { _controller: "AppBundle:Animaux:show" }
    methods:  GET

animaux_new:
    path:     /new/
    defaults: { _controller: "AppBundle:Animaux:new" }
    methods:  [GET, POST]

animaux_edit:
    path:     /{id}/edit/
    defaults: { _controller: "AppBundle:Animaux:edit" }
    methods:  [GET, PUT]

animaux_delete:
    path:     /{id}/delete/
    defaults: { _controller: "AppBundle:Animaux:delete" }
    methods:  DELETE

animaux_accouplement:
    path:     /accouplement/
    defaults: { _controller: "AppBundle:Animaux:accouplement" }
    methods:  [GET, POST]