app_default:
    resource: "@AppBundle/Resources/config/routing/index.yml"
    prefix:   /

app_animaux:
    resource: "@AppBundle/Resources/config/routing/animaux.yml"
    prefix:   /animaux

app_typeAnimaux:
    resource: "@AppBundle/Resources/config/routing/typeAnimaux.yml"
    prefix:   /type