services:
    app.entity.animaux:
        class: AppBundle\Entity\Animaux
    app.validateur.accouplement:
        class: AppBundle\Validateur\Accouplement
        arguments:
            - '@app.entity.animaux'
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
